export const ADD = "ADD";
export const SELECTED_ITEM = "SELECTED_ITEM";
export const CHAMP_SUCCESS = "CHAMP_SUCCESS";
export const CHAMP_ERROR = "CHAMP_ERROR";
export const CHAMP_BY_ID_SUCCESS = "CHAMP_BY_ID_SUCCESS";
export const CHAMP_BY_ID_ERROR = "CHAMP_BY_ID_ERROR";
export const CHAMP_FETCHING = "CHAMP_FETCHING";